if(NOT DEFINED YLKS_EXTENSION_SOURCE OR NOT DEFINED YLKS_EXTENSION_STAGE
   OR NOT DEFINED YLKS_SOLVER_LIBRARY)
    message(FATAL_ERROR "Extension source, stage and solver library are required")
endif()

file(REMOVE_RECURSE "${YLKS_EXTENSION_STAGE}")
file(MAKE_DIRECTORY "${YLKS_EXTENSION_STAGE}/bin")
file(COPY "${YLKS_EXTENSION_SOURCE}/"
     DESTINATION "${YLKS_EXTENSION_STAGE}"
     PATTERN "__pycache__" EXCLUDE)
file(COPY "${YLKS_SOLVER_LIBRARY}"
     DESTINATION "${YLKS_EXTENSION_STAGE}/bin")
file(WRITE "${YLKS_EXTENSION_STAGE}/.stage-complete" "staged\n")
