if(NOT DEFINED KOROMO_EXTENSION_SOURCE OR NOT DEFINED KOROMO_EXTENSION_STAGE
   OR NOT DEFINED KOROMO_SOLVER_LIBRARY)
    message(FATAL_ERROR "Extension source, stage and solver library are required")
endif()

file(REMOVE_RECURSE "${KOROMO_EXTENSION_STAGE}")
file(MAKE_DIRECTORY "${KOROMO_EXTENSION_STAGE}/bin")
file(COPY "${KOROMO_EXTENSION_SOURCE}/"
     DESTINATION "${KOROMO_EXTENSION_STAGE}"
     PATTERN "__pycache__" EXCLUDE)
file(COPY "${KOROMO_SOLVER_LIBRARY}"
     DESTINATION "${KOROMO_EXTENSION_STAGE}/bin")
file(WRITE "${KOROMO_EXTENSION_STAGE}/.stage-complete" "staged\n")
