if(NOT DEFINED KOROMO_EXTENSION_SOURCE OR NOT DEFINED KOROMO_EXTENSION_STAGE
   OR NOT DEFINED KOROMO_SOLVER_LIBRARY)
    message(FATAL_ERROR "Extension source, stage and solver library are required")
endif()

file(REMOVE_RECURSE "${KOROMO_EXTENSION_STAGE}")
file(MAKE_DIRECTORY "${KOROMO_EXTENSION_STAGE}/bin")
file(COPY "${KOROMO_EXTENSION_SOURCE}/"
     DESTINATION "${KOROMO_EXTENSION_STAGE}"
     PATTERN "__pycache__" EXCLUDE)
if(DEFINED KOROMO_EXTENSION_ID AND DEFINED KOROMO_EXTENSION_NAME)
    set(KOROMO_MANIFEST "${KOROMO_EXTENSION_STAGE}/blender_manifest.toml")
    file(READ "${KOROMO_MANIFEST}" KOROMO_MANIFEST_TEXT)
    string(REGEX REPLACE "id = \"[^\"]+\""
           "id = \"${KOROMO_EXTENSION_ID}\""
           KOROMO_MANIFEST_TEXT "${KOROMO_MANIFEST_TEXT}")
    string(REGEX REPLACE "name = \"[^\"]+\""
           "name = \"${KOROMO_EXTENSION_NAME}\""
           KOROMO_MANIFEST_TEXT "${KOROMO_MANIFEST_TEXT}")
    file(WRITE "${KOROMO_MANIFEST}" "${KOROMO_MANIFEST_TEXT}")
endif()
file(COPY "${KOROMO_SOLVER_LIBRARY}"
     DESTINATION "${KOROMO_EXTENSION_STAGE}/bin")
if(DEFINED KOROMO_CUDA_SOLVER_LIBRARY AND
   NOT KOROMO_CUDA_SOLVER_LIBRARY STREQUAL "")
    if(NOT EXISTS "${KOROMO_CUDA_SOLVER_LIBRARY}")
        message(FATAL_ERROR
            "CUDA solver library does not exist: ${KOROMO_CUDA_SOLVER_LIBRARY}")
    endif()
    file(COPY "${KOROMO_CUDA_SOLVER_LIBRARY}"
         DESTINATION "${KOROMO_EXTENSION_STAGE}/bin")
endif()
file(WRITE "${KOROMO_EXTENSION_STAGE}/.stage-complete" "staged\n")
